// Generated by SolidPython 1.1.3 on 2025-01-26 01:26:25


union() {
	translate(v = [0, 0, 20.0000000000]) {
		union() {
			cube(center = true, size = [25, 15, 40]);
			translate(v = [0, 0, 20.0000000000]) {
				cylinder(h = 8, r = 4);
			}
		}
	}
	translate(v = [0, 0, 60]) {
		difference() {
			sphere(r = 10);
			translate(v = [0, 0, -5.0000000000]) {
				cylinder(h = 10, r = 4.4000000000);
			}
		}
	}
	translate(v = [35, 0, 20.0000000000]) {
		rotate(a = [0, 90, 0]) {
			union() {
				cylinder(h = 35, r = 5);
				translate(v = [0, 0, 35]) {
					sphere(r = 4);
				}
			}
		}
	}
	translate(v = [-35, 0, 20.0000000000]) {
		rotate(a = [0, 90, 0]) {
			union() {
				cylinder(h = 35, r = 5);
				translate(v = [0, 0, 35]) {
					sphere(r = 4);
				}
			}
		}
	}
	translate(v = [8.3333333333, 0, -10]) {
		union() {
			cylinder(h = 45, r = 6);
			translate(v = [0, 0, 45]) {
				sphere(r = 4);
			}
			translate(v = [0, 0, 22.5000000000]) {
				sphere(r = 4);
			}
		}
	}
	translate(v = [-8.3333333333, 0, -10]) {
		union() {
			cylinder(h = 45, r = 6);
			translate(v = [0, 0, 45]) {
				sphere(r = 4);
			}
			translate(v = [0, 0, 22.5000000000]) {
				sphere(r = 4);
			}
		}
	}
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
from solid import *
from solid.utils import *
import math

class PrintInPlaceSoldier:
    def __init__(self):
        self.head_radius = 10
        self.body_width = 25
        self.body_height = 40
        self.body_depth = 15
        self.arm_length = 35
        self.arm_radius = 5
        self.leg_length = 45
        self.leg_radius = 6
        self.joint_radius = 4
        self.clearance = 0.4

    def create_head(self):
        # Create head with neck socket
        head = sphere(r=self.head_radius)
        socket = cylinder(r=self.joint_radius + self.clearance, h=self.head_radius)
        head = difference()(
            head,
            translate([0, 0, -self.head_radius/2])(socket)
        )
        return head

    def create_body(self):
        # Main body
        body = cube([self.body_width, self.body_depth, self.body_height], center=True)
        
        # Neck joint
        neck = cylinder(r=self.joint_radius, h=8)
        body = union()(
            body,
            translate([0, 0, self.body_height/2])(neck)
        )
        return body

    def create_arm(self, side=1):
        # Create arm with ball joint
        arm = cylinder(r=self.arm_radius, h=self.arm_length)
        ball = sphere(r=self.joint_radius)
        arm = union()(
            arm,
            translate([0, 0, self.arm_length])(ball)
        )
        return rotate([0, 90, 0])(arm)

    def create_leg(self, side=1):
        # Create leg with ball joints
        leg = cylinder(r=self.leg_radius, h=self.leg_length)
        hip_ball = sphere(r=self.joint_radius)
        knee_ball = sphere(r=self.joint_radius)
        
        leg = union()(
            leg,
            translate([0, 0, self.leg_length])(hip_ball),
            translate([0, 0, self.leg_length/2])(knee_ball)
        )
        return leg

    def generate_print_layout(self):
        # Layout all parts with proper spacing
        spacing = 10
        
        # Body at center
        assembly = translate([0, 0, self.body_height/2])(self.create_body())
        
        # Head above body
        head = translate([0, 0, self.body_height + self.head_radius + spacing])(
            self.create_head()
        )
        
        # Arms on sides
        right_arm = translate([self.body_width + spacing, 0, self.body_height/2])(
            self.create_arm(1)
        )
        left_arm = translate([-self.body_width - spacing, 0, self.body_height/2])(
            self.create_arm(-1)
        )
        
        # Legs below
        right_leg = translate([self.body_width/3, 0, -spacing])(
            self.create_leg(1)
        )
        left_leg = translate([-self.body_width/3, 0, -spacing])(
            self.create_leg(-1)
        )
        
        # Combine all parts
        assembly = union()(
            assembly,
            head,
            right_arm,
            left_arm,
            right_leg,
            left_leg
        )
        
        return assembly

    def save_stl(self):
        assembly = self.generate_print_layout()
        scad_render_to_file(assembly, 'soldier_toy_print.scad')
        print("OpenSCAD file generated. Please use OpenSCAD to export to STL.")

if __name__ == '__main__':
    soldier = PrintInPlaceSoldier()
    soldier.save_stl() 
 
************************************************/
